# Generated by Django 5.0.6 on 2024-05-16 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='created_at',
            new_name='createdAt',
        ),
    ]
